// data.jsx — product catalog, calculators, mock dashboard, schedule slots

const PRODUCTS = [
  {
    id: "cashflow",
    name_id: "Cashflow & Budgeting Tracker",
    name_en: "Cashflow & Budgeting Tracker",
    price: 39000,
    tag_id: "Paling laris",
    tag_en: "Best seller",
    icon: "Wallet",
    blurb_id: "Lacak pemasukan, pengeluaran, dan rasio menabung tiap bulan — tanpa drama spreadsheet.",
    blurb_en: "Track income, expenses, and savings rate every month — without the spreadsheet drama.",
    features_id: [
      "Auto-kategorisasi pengeluaran (12 kategori)",
      "Dashboard ringkas: cashflow, saving rate, top kategori",
      "Forecast bulanan & target tabungan",
      "Mobile-friendly tab di Google Sheets",
    ],
    features_en: [
      "Auto-categorize expenses (12 categories)",
      "Compact dashboard: cashflow, saving rate, top categories",
      "Monthly forecast & savings goal",
      "Mobile-friendly Google Sheets tab",
    ],
  },
  {
    id: "invest",
    name_id: "Investment Planning & Tracker",
    name_en: "Investment Planning & Tracker",
    price: 49000,
    tag_id: "Lengkap",
    tag_en: "Most complete",
    icon: "ChartBar",
    blurb_id: "Rencanakan target, hitung kontribusi bulanan, dan track portofolio dengan rebalance otomatis.",
    blurb_en: "Set targets, calculate monthly contribution, and track your portfolio with auto-rebalance hints.",
    features_id: [
      "Calculator return realistis (deposito, RDPU, RDS, saham)",
      "Tracker untuk reksadana, saham, emas, kripto",
      "Visualisasi compound interest 10–30 tahun",
      "Rebalance reminder & risk-profile checker",
    ],
    features_en: [
      "Realistic return calculator (deposit, MM fund, stocks)",
      "Tracker for mutual funds, stocks, gold, crypto",
      "Compound interest visual 10–30 years",
      "Rebalance reminder & risk-profile checker",
    ],
  },
  {
    id: "kpr",
    name_id: "Mortgage Planner",
    name_en: "Mortgage Planner",
    price: 55000,
    tag_id: "Premium",
    tag_en: "Premium",
    icon: "Home",
    blurb_id: "Sebelum tanda tangan akad KPR, hitung total bunga, simulasi tenor, dan strategi pelunasan dipercepat.",
    blurb_en: "Before signing your mortgage, calculate total interest, simulate tenors, and accelerated-payoff strategies.",
    features_id: [
      "Bandingkan 3 skenario KPR sekaligus",
      "Simulasi floating vs fixed",
      "Strategi pelunasan dipercepat (lump-sum, biweekly)",
      "Cek kemampuan bayar berdasarkan DSR",
    ],
    features_en: [
      "Compare 3 mortgage scenarios at once",
      "Floating vs fixed simulation",
      "Accelerated payoff strategies (lump-sum, biweekly)",
      "Affordability check based on DSR",
    ],
  },
  {
    id: "edu",
    name_id: "Education Planner",
    name_en: "Education Planner",
    price: 39000,
    tag_id: "Untuk orang tua",
    tag_en: "For parents",
    icon: "GraduationCap",
    blurb_id: "Berapa dana pendidikan anak — dari TK sampai universitas — di tengah inflasi pendidikan 10% per tahun.",
    blurb_en: "How much for your kid's education — from kindergarten to university — against 10% annual education inflation.",
    features_id: [
      "Database biaya 20+ universitas (domestik & LN)",
      "Inflasi pendidikan tahunan adjustable",
      "Strategi investasi sesuai timeline (5y, 10y, 17y)",
      "Buffer dana darurat khusus pendidikan",
    ],
    features_en: [
      "Cost database for 20+ universities (domestic & abroad)",
      "Adjustable annual education inflation",
      "Investment strategy by timeline (5y, 10y, 17y)",
      "Education-specific emergency buffer",
    ],
  },
  {
    id: "insurance",
    name_id: "Insurance Planning & Tracker",
    name_en: "Insurance Planning & Tracker",
    price: 39000,
    tag_id: "Wajib punya",
    tag_en: "Essential",
    icon: "ShieldCheck",
    blurb_id: "Hitung uang pertanggungan jiwa & kesehatan yang ideal sesuai income, tanggungan, dan utang.",
    blurb_en: "Calculate the right life & health coverage based on income, dependents, and debts.",
    features_id: [
      "Metode HLV, Income Replacement, & DIME",
      "Bandingkan term life vs whole life vs unit-link",
      "Audit polis yang sudah punya",
      "Checklist klaim kesehatan agar tidak ditolak",
    ],
    features_en: [
      "HLV, Income Replacement, & DIME methods",
      "Term vs whole vs unit-link comparison",
      "Audit your existing policy",
      "Claim checklist to avoid rejection",
    ],
  },
  {
    id: "pension",
    name_id: "Retirement & Estate Planner",
    name_en: "Retirement & Estate Planner",
    price: 39000,
    tag_id: "Untuk masa depan",
    tag_en: "Long-term",
    icon: "Gift",
    blurb_id: "Target pensiun yang realistis + rencana distribusi warisan sesuai prinsip syariah.",
    blurb_en: "A realistic retirement target + sharia-compliant estate distribution plan.",
    features_id: [
      "Hitung dana pensiun pakai metode 4% rule & dynamic withdrawal",
      "Simulasi withdrawal 25–40 tahun pensiun",
      "Distribusi warisan sesuai faraidh + wasiat 1/3",
      "Checklist dokumen warisan (akta, polis, properti)",
    ],
    features_en: [
      "Retirement fund via 4% rule & dynamic withdrawal",
      "25–40 year withdrawal simulation",
      "Faraidh distribution + 1/3 will",
      "Estate document checklist (deed, policy, property)",
    ],
  },
  {
    id: "bundle",
    name_id: "Paket Lengkap (Semua 6 Produk)",
    name_en: "Complete Bundle (All 6 Products)",
    price: 149000,
    tag_id: "Hemat 35%",
    tag_en: "Save 35%",
    icon: "Sparkle",
    blurb_id: "Semua 6 spreadsheet planner dalam satu paket — cashflow, investasi, rumah, pendidikan, asuransi, & pensiun.",
    blurb_en: "All 6 spreadsheet planners in one package — cashflow, investment, home, education, insurance, & retirement.",
    features_id: [
      "Cashflow & Budgeting Tracker",
      "Investment Planning & Tracker",
      "Mortgage Planner",
      "Education Planner",
      "Insurance Planning & Tracker",
      "Retirement & Estate Planner",
    ],
    features_en: [
      "Cashflow & Budgeting Tracker",
      "Investment Planning & Tracker",
      "Mortgage Planner",
      "Education Planner",
      "Insurance Planning & Tracker",
      "Retirement & Estate Planner",
    ],
  },
];

const CALCULATORS = [
  { id: "checkup", icon: "Sparkle", color: "#FFB800" },
  { id: "rumah", icon: "Home", color: "#FF9A6B" },
  { id: "edu", icon: "GraduationCap", color: "#C6F24E" },
  { id: "pension", icon: "Coins", color: "#E5A4FF" },
  { id: "warisan", icon: "Gift", color: "#FFD66B" },
  { id: "haji", icon: "Mosque", color: "#5EE5B0" },
  { id: "zakat", icon: "Heart", color: "#7C9CFF" },
  { id: "invest", icon: "ChartBar", color: "#C6F24E" },
  { id: "insurance", icon: "ShieldCheck", color: "#7C9CFF" },
];

const PAYMENT_METHODS = [
  { id: "qris", name: "QRIS", sub: "Scan & bayar dengan e-wallet apapun" },
  { id: "bank", name: "Transfer Bank", sub: "BCA · Mandiri · BNI", banks: ["BCA", "Mandiri", "BNI"] },
  { id: "ewallet", name: "E-Wallet", sub: "GoPay · OVO · Dana", wallets: ["GoPay", "OVO", "Dana"] },
];

const PROGRAMS = [
  {
    id: "warisan",
    icon: "Gift",
    color: "#FFB800",
    title_id: "Perencanaan Warisan",
    title_en: "Estate Planning",
    tagline_id: "Warisan cinta, bukan warisan hutang",
    tagline_en: "An inheritance of love, not of debt",
    desc_id: "Aset yang kamu kumpulin susah payah harus jadi milik keluarga — bukan jadi beban administrasi atau sumber konflik.",
    desc_en: "Assets you've built up should belong to your family — not become an admin burden or source of conflict.",
    benefits_id: [
      "Asuransi jiwa yang bikin keluarga tetap aman finansial",
      "Premium yang ditempatkan juga tumbuh nilainya",
      "Inheritance plan sesuai prinsip syariah (faraidh + wasiat)",
    ],
    benefits_en: [
      "Life insurance keeping your family financially secure",
      "Premiums that grow in value over time",
      "Sharia-compliant inheritance plan (faraidh + will)",
    ],
    ideal_id: "Cocok buat yang sudah established & punya keluarga",
    ideal_en: "For those established with a family",
  },
  {
    id: "utang",
    icon: "Coins",
    color: "#FF9A6B",
    title_id: "Pelunasan Utang",
    title_en: "Debt Protection",
    tagline_id: "Utang jangan jadi beban keluarga",
    tagline_en: "Don't let debt burden your family",
    desc_id: "KPR, mobil, atau pinjaman bisnis — semua bagus untuk pertumbuhan. Tapi siapa yang lunasi kalau kamu tiba-tiba ada apa-apa?",
    desc_en: "Mortgage, car, or business loans are all great for growth. But who covers them if something happens to you?",
    benefits_id: [
      "Cicilan otomatis lunas 100% kalau terjadi risiko",
      "Proses klaim cepat & transparan",
      "Bisa di-apply ke KPR, vehicle loan, business loan",
    ],
    benefits_en: [
      "Loans paid off 100% if something happens",
      "Fast & transparent claim process",
      "Works for mortgage, vehicle, and business loans",
    ],
    ideal_id: "Cocok buat yang baru ambil KPR atau cicilan besar",
    ideal_en: "For those with recent mortgage or major loans",
  },
  {
    id: "pendidikan",
    icon: "GraduationCap",
    color: "#C6F24E",
    title_id: "Pendidikan Anak",
    title_en: "Children's Education",
    tagline_id: "Anak kamu tetap sekolah, apapun yang terjadi",
    tagline_en: "Your kids stay in school — no matter what",
    desc_id: "Biaya pendidikan naik 10% per tahun. Plan-nya bukan sekadar nabung — tapi nabung yang dilindungi & tumbuh.",
    desc_en: "Education costs rise ~10% per year. The plan isn't just saving — it's protected, growing savings.",
    benefits_id: [
      "Tabungan khusus yang invest & tumbuh",
      "Pertanggungan agar pendidikan anak gak terhenti",
      "Pencairan flexible per fase (SD/SMP/SMA/Kuliah)",
    ],
    benefits_en: [
      "Dedicated savings that invest & grow",
      "Coverage ensures education never stops",
      "Flexible withdrawals per stage (primary / secondary / university)",
    ],
    ideal_id: "Cocok buat orang tua muda dengan planning matang",
    ideal_en: "For young parents with a solid plan",
  },
  {
    id: "investasi",
    icon: "ChartBar",
    color: "#5EE5B0",
    title_id: "Program Investasi",
    title_en: "Investment Program",
    tagline_id: "Duit kamu tumbuh dengan safety net lengkap",
    tagline_en: "Your money grows — with a full safety net",
    desc_id: "Nabung doang sudah gak cukup. Tapi investasi tanpa proteksi juga risiko. Solusi: investasi dengan asuransi terintegrasi.",
    desc_en: "Saving alone isn't enough. But investing without protection is risky. Solution: investment with integrated insurance.",
    benefits_id: [
      "Akses ke instrumen yang dikelola fund manager profesional",
      "Portofolio terdiversifikasi (saham, bond, money market)",
      "Asuransi terintegrasi dengan laporan transparan bulanan",
    ],
    benefits_en: [
      "Access to professional fund manager portfolios",
      "Diversified across stocks, bonds, money market",
      "Integrated insurance with transparent monthly reports",
    ],
    ideal_id: "Cocok buat long-term wealth building",
    ideal_en: "For long-term wealth building",
  },
  {
    id: "haji",
    icon: "Mosque",
    color: "#7C9CFF",
    featured: true,
    title_id: "Pelunasan Haji",
    title_en: "Hajj Savings",
    tagline_id: "Ibadah haji adalah impian — rencananya finansial",
    tagline_en: "Hajj is a spiritual dream — the plan is financial",
    desc_id: "Pergi haji dengan pikiran tenang, bukan parno biaya. Tabungan khusus dengan growth, dilindungi asuransi.",
    desc_en: "Go on Hajj with peace of mind, not financial anxiety. A dedicated growing fund, fully insured.",
    benefits_id: [
      "Tabungan khusus dengan return investasi syariah",
      "Asuransi proteksi — dana tetap aman buat keluarga",
      "Fleksibilitas: kapan ready berangkat, tinggal jalan",
    ],
    benefits_en: [
      "Dedicated savings with sharia-compliant returns",
      "Insurance protection — funds stay safe for family",
      "Flexible departure timing — go when you're ready",
    ],
    ideal_id: "Cocok buat yang serius merencanakan ibadah haji",
    ideal_en: "For those seriously planning their Hajj",
  },
  {
    id: "employee",
    icon: "Users",
    color: "#E5A4FF",
    title_id: "Employee Benefit",
    title_en: "Employee Benefit",
    tagline_id: "Tim yang sehat = bisnis yang jalan",
    tagline_en: "Healthy team = thriving business",
    desc_id: "Program untuk perusahaan — bikin tim merasa valued, terlindungi, fokus kerja tanpa parno biaya kesehatan.",
    desc_en: "For companies — making your team feel valued, protected, and focused without worrying about medical costs.",
    benefits_id: [
      "Paket asuransi kesehatan, jiwa, dan pensiun",
      "Retention rate naik — hemat biaya rekrutmen",
      "Compliance penuh + tax advantages + employer branding",
    ],
    benefits_en: [
      "Health, life, and pension insurance packages",
      "Higher retention — saves on recruitment costs",
      "Full compliance + tax advantages + employer branding",
    ],
    ideal_id: "Cocok buat bisnis yang lagi scale",
    ideal_en: "For businesses that are scaling",
  },
];

const WEBINARS = [
  {
    id: "w1",
    date_id: "15 Juni 2026",
    date_en: "June 15, 2026",
    time: "19:00 WIB",
    title_id: "Dari gaji ke kaya: strategi investasi buat milenial",
    title_en: "From paycheck to wealth: investment strategy for millennials",
    speaker: "Jasmine",
    format: "Online (Zoom)",
    spots_id: "Sisa 47 slot",
    spots_en: "47 spots left",
    free: true,
    tag_id: "PALING DITUNGGU",
    tag_en: "MOST AWAITED",
  },
  {
    id: "w2",
    date_id: "22 Juni 2026",
    date_en: "June 22, 2026",
    time: "14:00 WIB",
    title_id: "Perencanaan keuangan keluarga muda",
    title_en: "Financial planning for young families",
    speaker: "Jasmine",
    format: "Online + Offline Jakarta",
    spots_id: "Sisa 28 slot",
    spots_en: "28 spots left",
    free: true,
  },
  {
    id: "w3",
    date_id: "8 Juni 2026",
    date_en: "June 8, 2026",
    time: "19:00 WIB",
    title_id: "Asuransi jiwa sebagai foundation perencanaan",
    title_en: "Life insurance as the foundation of planning",
    speaker: "Jasmine",
    format: "Online (Zoom)",
    past: true,
    rating: 4.8,
    attendees: 250,
  },
];

const formatIDR = (n) =>
  "Rp " + new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(Math.round(n));

Object.assign(window, { PRODUCTS, CALCULATORS, PAYMENT_METHODS, PROGRAMS, WEBINARS, formatIDR });
